required-players: 1
countdown-seconds: 15
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  yaw: -180
  pitch: 0
arenas:
  0:
    lobby-spawn:
      world: 'world'
      x: 100
      y: 100
      z: 100
      yaw: -180
      pitch: 0
    team-spawns:
      blue:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
      red:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
  1:
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0